from pathlib import Path

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


### PLAYER CONSTANTS
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_INITIAL_ROTATION = 0
PLAYER_INITIAL_COOLDOWN_TIMER = 0
COOLDOWN_READY_THRESHOLD = 0
ASSETS_DIR = Path.cwd() / "assets"
FONTS_DIR = Path.cwd() / "fonts"

### DIRECTION UNIT OFFSETS (for edge / movement vectors)
DIRECTION_POSITIVE = 1
DIRECTION_NEGATIVE = -1
DIRECTION_NONE = 0
INITIAL_SPAWN_TIMER = 0.0
ANGLE_MIN_DEGREES = 0

### ASTEROID CONSTANTS
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

### SCORE
SCORE_PER_ASTEROID_HIT = 10

### AUDIO
AUDIO_FREQUENCY = 44100
AUDIO_SIZE = -16
AUDIO_CHANNELS = 2
AUDIO_BUFFER = 512
SHOOT_SOUND_VOLUME = 0.4

### GAME LOOP
TARGET_FPS = 60
BLINK_INTERVAL_MS = 500
BLINK_CYCLE_STATES = 2
MS_PER_SECOND = 1000
INITIAL_DT = 0.0
INITIAL_SCORE = 0
SCREEN_CENTER_DIVISOR = 2
BLACK_COMPONENT = 0

### FONTS
TITLE_FONT_SIZE = 120
PROMPT_FONT_SIZE = 48
FINAL_SCORE_FONT_SIZE = 48
SCORE_FONT_SIZE = 36

### LAYOUT OFFSETS (pixels, relative to screen center unless noted)
TITLE_CENTER_OFFSET_Y = -50
SPLASH_PROMPT_CENTER_OFFSET_Y = 80
FINAL_SCORE_CENTER_OFFSET_Y = 100
GAMEOVER_PROMPT_CENTER_OFFSET_Y = 200
GAMEOVER_PROMPT_SIDE_OFFSET_X = 250
SCORE_OFFSET_RIGHT = 20
SCORE_OFFSET_TOP = 20
ORIGIN_X = 0
ORIGIN_Y = 0
DIM_ALPHA = 120

### SPRITE / SHAPE OFFSETS
PLAYER_SPRITE_SCALE_FACTOR = 2.2
ASTEROID_SPRITE_SCALE_FACTOR = 2.2
PLAYER_SPRITE_ROTATION_OFFSET = 180
PLAYER_TRIANGLE_RIGHT_ANGLE = 90
PLAYER_TRIANGLE_WIDTH_DIVISOR = 1.5
PLAYER_FORWARD_X = 0
PLAYER_FORWARD_Y = 1

### ASTEROID OFFSETS
ASTEROID_MAX_SPIN_DEG_PER_SEC = 60
ASTEROID_SPLIT_ANGLE_MIN = 20
ASTEROID_SPLIT_ANGLE_MAX = 50
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2
ASTEROID_SPAWN_SPEED_MIN = 40
ASTEROID_SPAWN_SPEED_MAX = 100
ASTEROID_SPAWN_ANGLE_VARIATION = 30
ASTEROID_KIND_MIN = 1
SPAWN_POSITION_MIN = 0.0
SPAWN_POSITION_MAX = 1.0
FULL_CIRCLE_DEGREES = 360
